import type { Product } from '../types'

export const PRODUCTS: Product[] = [
  {
    id: 'P01',
    name: 'R-NMN',
    image: 'ia7035507475ff8b3',
    symptoms: ['疲労感', '体力低下', '老化'],
    effects: ['エネルギー産生', 'NAD+補充', '細胞修復'],
    ingredients: ['NMN (β-ニコチンアミドモノヌクレオチド)'],
    nutrientIds: ['N01'],
    memo: '',
  },
  {
    id: 'P02',
    name: 'NMN＆レスベラトロール',
    image: 'ib3fdbcb08238620b',
    symptoms: ['老化', '疲労感', '血流低下'],
    effects: ['抗老化', 'サーチュイン活性化', 'エネルギー産生'],
    ingredients: ['NMN', 'レスベラトロール'],
    nutrientIds: ['N01', 'N02'],
    memo: '',
  },
  {
    id: 'P03',
    name: 'レシチン・γリノレン酸 90粒',
    image: 'ia114042ef6c6982b',
    symptoms: ['コレステロール高め', '肌荒れ', '脳機能低下'],
    effects: ['脂質代謝改善', '細胞膜強化', '脳活性化'],
    ingredients: ['大豆レシチン', 'γリノレン酸 (GLA)'],
    nutrientIds: ['N03', 'N04'],
    memo: '',
  },
  {
    id: 'P04',
    name: 'レシチン・γリノレン酸 150粒',
    image: 'ife88f2465e31fb00',
    symptoms: ['コレステロール高め', '肌荒れ', '脳機能低下'],
    effects: ['脂質代謝改善', '細胞膜強化', '脳活性化'],
    ingredients: ['大豆レシチン', 'γリノレン酸 (GLA)'],
    nutrientIds: ['N03', 'N04'],
    memo: '',
  },
  {
    id: 'P05',
    name: 'オメガ3 α-55 premium',
    image: 'i2db347fdd9ea6b2d',
    symptoms: ['血流低下', '中性脂肪高め', '炎症'],
    effects: ['血液サラサラ', '中性脂肪低下', '抗炎症'],
    ingredients: ['EPA', 'DHA', 'α-リノレン酸'],
    nutrientIds: ['N05', 'N06'],
    memo: '',
  },
  {
    id: 'P06',
    name: 'コエンザイムQ10',
    image: '',
    symptoms: ['疲労感', '心臓機能低下', '老化'],
    effects: ['エネルギー産生', '抗酸化', '心臓保護'],
    ingredients: ['コエンザイムQ10 (ユビキノン)'],
    nutrientIds: ['N07'],
    memo: '',
  },
  {
    id: 'P07',
    name: 'アスタキサンチン',
    image: '',
    symptoms: ['眼精疲労', '肌老化', '酸化ストレス'],
    effects: ['強力抗酸化', '眼疲労回復', '美肌'],
    ingredients: ['アスタキサンチン'],
    nutrientIds: ['N08'],
    memo: '',
  },
  {
    id: 'P08',
    name: 'ビタミンC 1000mg',
    image: '',
    symptoms: ['免疫力低下', '肌荒れ', '疲労感'],
    effects: ['免疫強化', 'コラーゲン生成', '抗酸化'],
    ingredients: ['L-アスコルビン酸'],
    nutrientIds: ['N09'],
    memo: '',
  },
  {
    id: 'P09',
    name: 'ビタミンD3',
    image: '',
    symptoms: ['免疫力低下', '骨密度低下', '気分低下'],
    effects: ['免疫調整', '骨強化', '気分改善'],
    ingredients: ['コレカルシフェロール (D3)'],
    nutrientIds: ['N10'],
    memo: '',
  },
  {
    id: 'P10',
    name: 'ビタミンB群コンプレックス',
    image: '',
    symptoms: ['疲労感', '神経過敏', 'エネルギー不足'],
    effects: ['エネルギー代謝', '神経機能正常化', '疲労回復'],
    ingredients: ['B1', 'B2', 'B3', 'B5', 'B6', 'B7', 'B9', 'B12'],
    nutrientIds: ['N11'],
    memo: '',
  },
  {
    id: 'P11',
    name: 'マグネシウム',
    image: '',
    symptoms: ['筋肉けいれん', '睡眠障害', 'ストレス'],
    effects: ['筋肉弛緩', '睡眠改善', 'ストレス軽減'],
    ingredients: ['グリシン酸マグネシウム'],
    nutrientIds: ['N12'],
    memo: '',
  },
  {
    id: 'P12',
    name: '亜鉛',
    image: '',
    symptoms: ['免疫力低下', '味覚障害', '肌荒れ'],
    effects: ['免疫強化', '味覚正常化', '皮膚修復'],
    ingredients: ['グルコン酸亜鉛'],
    nutrientIds: ['N13'],
    memo: '',
  },
  {
    id: 'P13',
    name: 'プロバイオティクス',
    image: '',
    symptoms: ['腸内環境悪化', '免疫力低下', '便秘'],
    effects: ['腸内フローラ改善', '免疫調整', '便通改善'],
    ingredients: ['乳酸菌', 'ビフィズス菌', 'プレバイオティクス'],
    nutrientIds: ['N14'],
    memo: '',
  },
  {
    id: 'P14',
    name: 'グルタチオン',
    image: '',
    symptoms: ['酸化ストレス', '解毒機能低下', '肌くすみ'],
    effects: ['強力抗酸化', '肝臓デトックス', '美白'],
    ingredients: ['還元型グルタチオン'],
    nutrientIds: ['N15'],
    memo: '',
  },
  {
    id: 'P15',
    name: 'αリポ酸',
    image: '',
    symptoms: ['血糖値高め', '酸化ストレス', '神経障害'],
    effects: ['血糖調整', '抗酸化', '神経保護'],
    ingredients: ['αリポ酸 (チオクト酸)'],
    nutrientIds: ['N16'],
    memo: '',
  },
  {
    id: 'P16',
    name: 'L-カルニチン',
    image: '',
    symptoms: ['体重増加', '疲労感', '運動能力低下'],
    effects: ['脂肪燃焼促進', 'エネルギー産生', '運動パフォーマンス向上'],
    ingredients: ['L-カルニチン酒石酸塩'],
    nutrientIds: ['N17'],
    memo: '',
  },
  {
    id: 'P17',
    name: 'ベルベリン',
    image: '',
    symptoms: ['血糖値高め', 'コレステロール高め', '腸内環境悪化'],
    effects: ['血糖調整', '脂質改善', '抗菌'],
    ingredients: ['ベルベリン塩酸塩'],
    nutrientIds: ['N18'],
    memo: '',
  },
  {
    id: 'P18',
    name: 'クルクミン (ターメリック)',
    image: '',
    symptoms: ['炎症', '関節痛', '消化不良'],
    effects: ['抗炎症', '関節保護', '消化促進'],
    ingredients: ['クルクミン', 'ピペリン (吸収促進)'],
    nutrientIds: ['N19'],
    memo: '',
  },
  {
    id: 'P19',
    name: 'GABA',
    image: '',
    symptoms: ['ストレス', '睡眠障害', '不安感'],
    effects: ['リラックス効果', '睡眠改善', '抗ストレス'],
    ingredients: ['γアミノ酪酸 (GABA)'],
    nutrientIds: ['N20'],
    memo: '',
  },
  {
    id: 'P20',
    name: 'テアニン',
    image: '',
    symptoms: ['ストレス', '集中力低下', '睡眠障害'],
    effects: ['リラックス', '集中力向上', '睡眠質改善'],
    ingredients: ['L-テアニン'],
    nutrientIds: ['N21'],
    memo: '',
  },
  {
    id: 'P21',
    name: 'アシュワガンダ',
    image: '',
    symptoms: ['ストレス', '疲労感', 'テストステロン低下'],
    effects: ['アダプトゲン', '疲労軽減', 'ホルモンバランス改善'],
    ingredients: ['アシュワガンダ根エキス (KSM-66)'],
    nutrientIds: ['N22'],
    memo: '',
  },
  {
    id: 'P22',
    name: 'ライオンズメイン (ヤマブシタケ)',
    image: '',
    symptoms: ['認知機能低下', '神経障害', '記憶力低下'],
    effects: ['神経成長因子促進', '認知機能改善', '神経保護'],
    ingredients: ['ヤマブシタケ菌糸体エキス'],
    nutrientIds: ['N23'],
    memo: '',
  },
  {
    id: 'P23',
    name: 'カルシウム・マグネシウム・ビタミンD',
    image: '',
    symptoms: ['骨密度低下', '筋肉けいれん', '歯の弱化'],
    effects: ['骨強化', '筋肉機能正常化', '歯の健康維持'],
    ingredients: ['炭酸カルシウム', 'グリシン酸マグネシウム', 'ビタミンD3'],
    nutrientIds: ['N10', 'N12', 'N24'],
    memo: '',
  },
  {
    id: 'P24',
    name: 'ヒアルロン酸・コラーゲン',
    image: '',
    symptoms: ['肌乾燥', '関節痛', '肌弾力低下'],
    effects: ['保湿', '関節潤滑', '肌弾力改善'],
    ingredients: ['ヒアルロン酸', '加水分解コラーゲン (魚由来)'],
    nutrientIds: ['N25', 'N26'],
    memo: '',
  },
  {
    id: 'P25',
    name: 'ルテイン・ゼアキサンチン',
    image: '',
    symptoms: ['眼精疲労', '視力低下', 'ブルーライト障害'],
    effects: ['眼疲労回復', '黄斑保護', 'ブルーライトカット'],
    ingredients: ['ルテイン', 'ゼアキサンチン'],
    nutrientIds: ['N27'],
    memo: '',
  },
  {
    id: 'P26',
    name: 'ミネラルコンプレックス',
    image: '',
    symptoms: ['ミネラル不足', '疲労感', '免疫力低下'],
    effects: ['ミネラル補充', '電解質バランス', '酵素補助'],
    ingredients: ['鉄', 'カルシウム', 'マグネシウム', '亜鉛', 'セレン', 'クロム'],
    nutrientIds: ['N12', 'N13', 'N24', 'N28'],
    memo: '',
  },
]

export const IMAGE_BASE = 'https://image.jimcdn.com/app/cms/image/transf/none/path/s6d4d15d6e7c4e3f7/image/'

export function productImageUrl(imageId: string): string {
  if (!imageId) return ''
  return `${IMAGE_BASE}${imageId}/version/1744688141/image.jpg`
}
