import type { Product } from '../types'

// ── サプリメント (S01-S26) ────────────────────────────────────────────────────

export const PRODUCTS: Product[] = [
  {
    id: 'S01',
    name: 'R-NMN',
    image: 'ia7035507475ff8b3',
    category: 'supplement',
    description: '長寿遺伝子(サーチュイン)の活性化に直接働きかけるNMNサプリ。特殊カプセルで有効成分を腸まで届ける。',
    price: 129600,
    volume: '445mg×30粒',
    ingredients: ['β-ニコチンアミド・モノヌクレオチド(国内製造)', 'ニコチン酸アミド', 'コエンザイムQ１０', 'HPMC', 'L-トリプトファン', 'ビタミンC', 'ビタミンE', 'ビタミンB2', 'ビタミンB6', 'ビタミンB1', 'ビタミンA', '葉酸', 'ビタミンK', 'ビオチン', 'ビタミンD', 'ビタミンB12', '赤ワインエキス末', 'パントテン酸カルシウム'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S02',
    name: 'NMN＆レスベラトロール・酵素ゼリー',
    image: 'ib3fdbcb08238620b',
    category: 'supplement',
    description: 'NMNとレスベラトロールを同時配合した酵素ゼリー。相乗効果でサーチュイン活性化を促進。',
    price: 32400,
    volume: '15g×30本',
    ingredients: ['果糖ブドウ糖液糖(国内製造)', 'イソマルトオリゴ糖', '難消化性デキストリン', '植物発酵エキス', 'β-ニコチンアミド・モノヌクレオチド', '赤ワインエキス末（レスベラトロール含有）', '鮫軟骨抽出末（コンドロイチン含有）', 'コラーゲンペプチド', 'ヒアルロン酸'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S03',
    name: 'レシチン・γリノレン酸 90粒',
    image: 'ia114042ef6c6982b',
    category: 'supplement',
    description: '身体の全ての細胞に必要なレシチンと、アレルギー症状に関わる必須脂肪酸γ-リノレン酸を配合。',
    price: 10800,
    volume: '550mg×90粒',
    ingredients: ['レシチン(大豆由来)(国内製造)', 'ボラージシード油(国内製造)', 'シソ油(国内製造)', 'ゼラチン', 'グリセリン', 'ミツロウ'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S04',
    name: 'レシチン・γリノレン酸 150粒',
    image: 'ife88f2465e31fb00',
    category: 'supplement',
    description: '身体の全ての細胞に必要なレシチンと、アレルギー症状に関わる必須脂肪酸γ-リノレン酸を配合。大容量タイプ。',
    price: 16200,
    volume: '550mg×150粒',
    ingredients: ['レシチン(大豆由来)(国内製造)', 'ボラージシード油(国内製造)', 'シソ油(国内製造)', 'ゼラチン', 'グリセリン', 'ミツロウ'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S05',
    name: 'レシチン＆リノレン酸ゼリー',
    image: 'i65683f6d0e0456b4',
    category: 'supplement',
    description: 'レシチン・ボラージシード油・シソ油をゼリータイプで手軽に摂取。',
    price: 21600,
    volume: '15g×30本',
    ingredients: ['果糖ブドウ糖液糖(国内製造)', 'ボラージシード油', 'シソ油', 'トレハロース', '酵素分解レシチン(大豆由来)', 'ビオチン', 'ゲル化剤(増粘多糖類)', '香料', '甘味料(ステビア、ソーマチン)', 'クエン酸'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S06',
    name: 'ハーブ活力サプリ',
    image: 'ib80a7ed1597e2975',
    category: 'supplement',
    description: '中国漢方・インドアーユルヴェーダ・南米民間療法のハーブを配合。世界中の選りすぐりの成分で活力をバックアップ。',
    price: 21600,
    volume: '427mg×30粒',
    ingredients: ['ガラナ(ブラジル製造)', 'アリ粉末', 'マカ粉末', 'アカガウクルア', 'L-シトルリン', 'ゴツコーラエキス', 'タツノオトシゴ粉末', 'ゼラチン', '結晶セルロース', 'ショ糖脂肪酸エステル'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S07',
    name: 'ラクトフェリン',
    image: 'i46945159906befc6',
    category: 'supplement',
    description: '哺乳類の母乳に含まれる生体防御タンパク質。菌が侵入しやすい箇所を守り免疫を強化。',
    price: 16200,
    volume: '250mg×60粒',
    ingredients: ['ホエイパウダー（乳成分を含む）(オーストラリア製造)', 'ドロマイト', '亜鉛含有酵母', 'ヨーグルトパウダー（乳成分を含む）', '還元麦芽糖水飴', 'イソマルトオリゴ糖粉あめ', 'ラクトフェリン（乳由来）', 'クエン酸', 'ビタミンC', '葉酸', 'ビタミンB１２'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S08',
    name: 'ブラックジンジャー',
    image: 'i70085f0964c2024d',
    category: 'supplement',
    description: 'ポリメトキシフラボン含有のブラックジンジャーをはじめ厳選ハーブを配合。代謝促進・血流・リンパ・ダイエットをサポート。',
    price: 16200,
    volume: '430mg×60粒',
    ingredients: ['ブラックジンジャー抽出物(国内製造)', '緑茶ポリフェノール', 'ターミナリアベレリカ抽出物', 'サラシア抽出物', 'ゴツコラエキス末', '桑の葉エキス', 'ヒハツ抽出物', 'L-カルニチンL-酒石酸塩', 'L-アルギニン', 'L-リジン塩酸塩', 'ビタミンB1', 'ビタミンB2', 'ビタミンB6'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S09',
    name: '燃焼系サプリ 26成分',
    image: 'if621f8e3ecfe11f2',
    category: 'supplement',
    description: 'Co-Q10・α-リポ酸・L-カルニチン等26種類の有効成分が燃焼をサポート。',
    price: 10800,
    volume: '320mg×90粒',
    ingredients: ['玉葱エキス末(国内製造)', 'L-カルニチンL-酒石酸塩', 'α-リポ酸', 'コエンザイムＱ１０', '紅麴', 'イチョウ葉エキス末', 'グァバ葉エキス末', 'ガルシニアエキス末', 'バナバ末', '無臭ニンニクエキス末', 'Ｌ-シトルリン', 'ゴツコーラエキス', 'サラシアレティキュラータエキス', '桑の葉エキス末', 'ギムネマシルベスタ抽出物', 'ショウガエキス末', 'γ-アミノ酪酸', 'ガラナ末', 'キダチアロエ末', '亜鉛含有酵母', 'セレン含有酵母', 'クロム含有酵母', '唐辛子粉末'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S10',
    name: 'ビルベリー (目のサプリ)',
    image: 'i29cc9d7d03e2427a',
    category: 'supplement',
    description: 'アントシアニン含有量がブルーベリーの3〜5倍のビルベリー、ルテイン、メグスリノキを配合。',
    price: 10800,
    volume: '460mg×60粒',
    ingredients: ['サフラワー油(国内製造)', 'ビルベリーエキス末', 'メグスリノキ粉末', 'ビタミンE', 'β-カロテン', 'マリーゴールド色素', 'ビタミンB1', 'ビタミンB6', 'ビタミンB12', 'ゼラチン', 'グリセリン', 'グリセリン脂肪酸エステル', 'ミツロウ'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S11',
    name: 'スーパーコンドロイチン＆コラーゲン',
    image: 'i00435ba1205d3a23',
    category: 'supplement',
    description: '軟骨構成要素のコンドロイチン・グルコサミン・コラーゲンにMSM・デビルズクローを高配合。',
    price: 5400,
    volume: '250mg×120粒',
    ingredients: ['乳糖(ドイツ製造)', 'コラーゲンペプチド(フランス製造)', 'メチルサルフォニルメタン', 'デキストリン', 'グルコサミン（かにを含む）', 'サメ軟骨抽出物', 'デビルズクローエキス', '結晶セルロース', 'ショ糖脂肪酸エステル'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S12',
    name: 'マルチビタミン＆ミネラル',
    image: 'i5d520639bdd85989',
    category: 'supplement',
    description: '13種類のビタミン・12種類のミネラルをバランスよく配合。日本人に不足しがちな成分を効率よく摂取。',
    price: 5400,
    volume: '350mg×60粒',
    ingredients: ['還元麦芽糖水飴(国内製造)', 'ビタミンE（植物油）', '亜鉛含有酵母', 'マンガン含有酵母', 'セレン含有酵母', 'クロム含有酵母', 'ヨウ素含有酵母', '卵殻カルシウム（未焼成）', 'ビタミンC', '酸化マグネシウム', '塩化カリウム', 'リン酸三カルシウム', 'ピロリン酸第二鉄', 'グルコン酸銅', 'ビタミンA', 'ビタミンB1', 'ビタミンB2', 'ビタミンB6', 'ビタミンB12', 'ビタミンD', 'ビタミンK', '葉酸', 'ビオチン'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S13',
    name: 'ガラナ',
    image: 'i5697c6980b1920f5',
    category: 'supplement',
    description: '南米アマゾンの先住民に愛されたガラナ。亜熱帯地方特有の植物で、貴重な薬用品として幅広く利用。',
    price: 16200,
    volume: '250mg×120粒',
    ingredients: ['ガラナ末(ブラジル製造)', '麦芽糖', '結晶セルロース', 'ショ糖脂肪酸エステル', '微粒二酸化ケイ素', '安定剤(グァーガム)'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S14',
    name: '柿タンニン (消臭・抗菌)',
    image: 'iabae14a8e0cb88bd',
    category: 'supplement',
    description: '柿タンニンの消臭・抗菌作用は緑茶カテキンの約30倍。悪臭成分と結合し臭いを元から絶つ。',
    price: 10800,
    volume: '800mg×60粒',
    ingredients: ['柿抽出物(国内製造)', '甘味料（ソルビトール、アスパルテーム・L-フェニルアラニン化合物、アセスルファムK）', 'トレハロース', 'クエン酸', '環状オリゴ糖', 'ショ糖脂肪酸エステル', '香料', '二酸化ケイ素', '炭酸ナトリウム'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S15',
    name: 'ムコ多糖＆酵素ゼリーロイヤルDX',
    image: 'ic8553fc5ebc53a1d',
    category: 'supplement',
    description: 'ヒアルロン酸・コンドロイチン・コラーゲン・ローヤルゼリーに加え80種類以上の原料から生成した酵素エキスのゼリー。',
    price: 10800,
    volume: '15g×30本',
    ingredients: ['果糖ブドウ糖液糖（国内製造）', 'イソマルトオリゴ糖', '難消化性デキストリン', 'フィッシュコラーゲンペプチド', '植物発酵エキス', 'ローヤルゼリー', '鮫軟骨抽出物（コンドロイチン含有）', 'ヒアルロン酸', 'ゲル化剤（増粘多糖類）', 'クエン酸', '香料'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S16',
    name: '腸活ゼリー',
    image: 'i1de571857a9f72c3',
    category: 'supplement',
    description: '腸内をキレイにすることで全身の美容と健康につながる。便秘・肌荒れ・ニキビ・アレルギーでお悩みの方へ。',
    price: 5400,
    volume: '15g×15本',
    ingredients: ['果糖ブドウ糖液糖(国内製造）', 'イソマルトオリゴ糖', '難消化性デキストリン', 'キャンドルブッシュ末', 'グレープフルーツ果汁', 'キダチアロエエキス末', 'モズク抽出エキス末', '乳酸球菌FK-23菌粉末', 'ゲル化剤（増粘多糖類）', '香料', '酸味料'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S17',
    name: '白トリュフ酵素ゼリー',
    image: 'i9d08adafba148bc3',
    category: 'supplement',
    description: '「白トリュフエキス」と91種類の原料から生成した「酵素エキス」を配合した美容ゼリー。',
    price: 5400,
    volume: '15g×30本',
    ingredients: ['果糖ブドウ糖液糖（国内製造）', 'プルーン果汁', 'エリスリトール', 'フィッシュコラーゲンペプチド', '野草発酵エキス', 'トリュフ抽出液', 'ベリー混合エキス末（ワイルドブルーベリーエキス、ストロベリーエキス、クランベリーエキス、ラズベリー種子エキス）', 'ヒアルロン酸', 'ビタミンC'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S18',
    name: '水溶性プロポリス（顆粒）',
    image: 'i3f63a37893afb5f5',
    category: 'supplement',
    description: 'プロポリスは天然の抗生物質と言われる蜂の巣成分。ローヤルゼリーと配合した高濃度顆粒タイプ。',
    price: 32400,
    volume: '2000mg×30包',
    ingredients: ['プロポリスエキス末(国内製造)', 'デキストリン', '乳糖', 'ローヤルゼリー', 'ポリデキストロース', '果糖', 'ブドウ糖', '麦芽糖', 'ビタミンプレミックス'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S19',
    name: '水溶性プロポリス原液',
    image: 'iaaee11af4cde65ce',
    category: 'supplement',
    description: 'ブラジル産プロポリスを純水により抽出。アルコール抽出よりも飲みやすく、アレルギーの心配もない。',
    price: 32400,
    volume: '100ml',
    ingredients: ['プロポリス抽出液(国内製造)', 'ナトリウム(Na)'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S20',
    name: '鹿角霊芝ドリンク',
    image: 'i3b27318a65748366',
    category: 'supplement',
    description: '漢方で"上品"として珍重される鹿角霊芝。β-Dグルカンはアガリクスの6倍含有。ゲルマニウムをはじめとする有効成分が注目。',
    price: 21600,
    volume: '50ml×10本',
    ingredients: ['鹿角霊芝抽出液(国内製造)', 'オリゴ糖シラップ', '還元麦芽糖水飴', 'エリスリトール', 'ローヤルゼリー抽出物', '冬虫夏草エキス', 'ショウガエキス', 'カキ肉抽出物', 'サイクロデキストリン', 'ビタミンC', '酸味料', '香料'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S21',
    name: '鹿角霊芝原液',
    image: '',
    category: 'supplement',
    description: '貴重な鹿角霊芝の原液100％。豊富に含まれるβ-Dグルカンは免疫を正常化させてアレルギー症状を改善。',
    price: 32400,
    volume: '100ml',
    ingredients: ['鹿角霊芝抽出液(国内製造)'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S22',
    name: '馬プラセンタ+世界三大医薬品',
    image: '',
    category: 'supplement',
    description: '馬プラセンタとシベリアカラマツ・イチョウ葉・フランス海岸松樹皮エキス「世界三大医薬品」を同時配合した最高峰サプリ。',
    price: 32400,
    volume: '303mg×60粒',
    ingredients: ['馬プラセンタエキスパウダー（国内製造）', 'シベリアカラマツ形成層及び木部由来抽出物', 'イチョウ葉エキス', 'ゴツコーラエキス', 'L-シトルリン', 'ヒバマタ粉末', 'フランス海岸松樹皮エキス', 'マルトデキストリン', 'L-アルギニン', '結晶セルロース', 'ゼラチン'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S23',
    name: '燕窩コラーゲン',
    image: '',
    category: 'supplement',
    description: '燕の巣が持つシアル酸・上皮細胞増殖因子(EGF)・線維芽細胞増殖因子(FGF)を含む高い美容効果。',
    price: 32400,
    volume: '50ml×10本',
    ingredients: ['コラーゲンペプチド(国内製造)', 'ゼラチン', 'エリスリトール', 'マルチトール', 'ローヤルゼリー', '酵素処理燕窩', 'ビタミンC', 'ビオチン', 'ビタミンB6', 'セラミド', 'L-アルギニン', 'ヒアルロン酸', 'ザクロ果汁', '香料'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S24',
    name: 'プラセンタクオリティ',
    image: '',
    category: 'supplement',
    description: '純国産サラブレットプラセンタを使用。ラクトフェリン・CoQ-10・α-リポ酸・ビオチン・カルニチンを配合。',
    price: 32400,
    volume: '2000mg×30包',
    ingredients: ['馬プラセンタエキス末（国内製造）', 'マルチトール', '難消化性デキストリン', 'ラクトフェリン', 'L-カルニチンL-酒石酸塩', 'コエンザイムQ10', 'αーリポ酸', 'パラチノース', 'デキストリン', 'クエン酸', 'DL-リンゴ酸', 'ビタミンC', 'ビオチン', '香料'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S25',
    name: 'プエラリア＆イソフラボン',
    image: '',
    category: 'supplement',
    description: '輝く美肌とボディラインのためのプエラリアとイソフラボン、美白のL-シスチンなどを配合。',
    price: 0,
    volume: '263mg×30粒',
    ingredients: ['プエラリア・ミリフィカ', 'ローズヒップパウダー', 'ビール酵母（亜鉛含有）', 'シルク加水分解物', '大豆胚芽抽出物（イソフラボン含有）', 'ビタミンＥ含有植物油脂', 'ローヤルゼリー末', '鶏冠抽出物（ヒアルロン酸、コラーゲン含有）', 'シャンピニオンエキス', 'コロハエキス末', '黒コショウ抽出物', 'Ｌ-シスチン', 'ビタミンＢ12', 'ビタミンＢ6'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'S26',
    name: 'オメガ3 α-55 premium',
    image: 'i2db347fdd9ea6b2d',
    category: 'supplement',
    description: 'α-リノレン酸が豊富な必須脂肪酸サプリ。毎日の食事で不足しがちなオメガ3系脂肪酸を補給。',
    price: 19440,
    volume: '150ml',
    ingredients: ['α-リノレン酸 (シソ油・エゴマ油由来)'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },

  // ── コスメティック (C01-C28) ────────────────────────────────────────────────

  {
    id: 'C01',
    name: 'NAジェル',
    image: 'i88bf73de2b75526a',
    category: 'cosmetic',
    description: 'ナイアシンアミド・ヒト幹細胞エキス・プロテオグリカン・オクラ種子エキスなどが配合。ハリのある生き生きとした肌へ導くオールインワンジェル。',
    price: 30800,
    volume: '50g',
    ingredients: ['ナイアシンアミド', 'ヒト幹細胞エキス', 'プロテオグリカン', 'イタドリエキス', 'オクラ種子エキス', 'ツボクサエキス', 'ヒアルロン酸', 'プラセンタエキス', 'ビオチン', 'ユズ果実エキス', 'オウゴン根エキス', 'カミツレ花エキス', 'カンゾウ根エキス', 'チャ葉エキス', 'ローズマリー葉エキス'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C02',
    name: 'N-BBリッチクリーム (NMN＆幹細胞エキス配合)',
    image: 'ie8d57b12f286b09a',
    category: 'cosmetic',
    description: 'NMN・リンゴ幹細胞・エーデルワイス幹細胞をはじめとした贅沢成分を配合した最高峰リッチクリーム。',
    price: 165000,
    volume: '50g',
    ingredients: ['リンゴ幹細胞(リンゴ果実培養細胞エキス)', 'エーデルワイス幹細胞(エーデルワイスカルス培養エキス)', 'プロポリス', 'ローヤルゼリー', 'プラセンタエキス', 'Co-Q10(ユビキノン)', 'α-リポ酸(チオクト酸)', 'カルニチン', 'EGF(ヒトオリゴペプチド‐1)', 'FGF(ヒトオリゴペプチド‐13)', 'IGF(ヒトオリゴペプチド‐21)', 'イチョウ葉', '月見草油', 'ナツメ果実', 'ヒアルロン酸', 'コンドロイチン', 'リピジュア(ポリクオタニウム‐51)', 'ホホバ種子油', 'ビフィズス菌培養溶解質', '加水分解エラスチン', 'ラクトフェリン(牛乳)', '加水分解シルク', 'プエラリアミリフィカ根エキス', 'ビオチン', 'ツボクサエキス', 'アロエベラ葉エキス'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C03',
    name: 'BBリッチクリーム',
    image: 'i94a0b83a486ee4c9',
    category: 'cosmetic',
    description: '高級美容成分を贅沢に配合したリッチクリーム。EGF・FGF・幹細胞エキス・プラセンタなど約30種の成分配合。',
    price: 88000,
    volume: '50g',
    ingredients: ['リンゴ果実培養エキス', 'エーデルワイスカルス培養エキス', 'プロポリスエキス', 'アスコルビン酸メチルシラノール', 'プラセンタ', 'ピクノジェノール(フランスカイガンショウ樹皮エキス)', 'EGF(ヒトオリゴペプチド-1)', 'FGF', 'IGF', 'ホホバ種子油', 'デルマタン硫酸Na', 'Co-Q10(ユビキノン)', 'αリポ酸(チオクト酸)', 'ビフィズス菌培養溶解質', 'ヒアルロン酸Na', 'ローヤルゼリーエキス', '加水分解エラスチン', 'ポリクオタニウム-51', 'ラクトフェリン(牛乳)', '加水分解シルク', 'プエラリアミリフィカ根エキス', 'ビオチン'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C04',
    name: 'エッセンスソープ',
    image: 'i7f79d4c0582eac72',
    category: 'cosmetic',
    description: '美容液で洗う最高級ソープ。ヤシ油系洗浄成分で肌を優しく洗いながら美容液成分もたっぷり配合。',
    price: 22000,
    volume: '120ml',
    ingredients: ['リンゴ果実培養エキス', 'エーデルワイスカルス培養エキス', 'ヒアルロン酸Na', 'ローヤルゼリーエキス', 'αリポ酸(チオクト酸)', 'ビフィズス菌培養質', '加水分解シルク', 'オレンジ油'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C05',
    name: 'NAローション (ハーブ配合)',
    image: 'i306d7b5d2ea6e439',
    category: 'cosmetic',
    description: 'シミ・くすみから肌を守るハーブ配合ローション。ブドウ果実細胞エキス・ホホバ種子油・ラクトフェリン配合。',
    price: 11000,
    volume: '30ml',
    ingredients: ['ブドウ果実細胞エキス', 'ヒアルロン酸Na', 'アロエベラ葉エキス', 'ホホバ種子油', 'オウゴン根エキス', 'ローズマリー葉エキス', 'ラクトフェリン(牛乳)', 'レシチン'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C06',
    name: 'リフトジェルGOLD',
    image: 'ib0364a80f9e44df8',
    category: 'cosmetic',
    description: 'たくさんの美容効果を一つで実現。スリムアップのサポートにも対応するパーフェクトジェル。',
    price: 27500,
    volume: '50g',
    ingredients: ['ピクノジェノール(フランスカイガンショウ樹皮エキス)', '月見草油', 'ナツメ果実エキス', 'αリポ酸(チオクト酸)', 'Co-Q10(ユビキノン)', 'ビオチン', 'イチョウ葉エキス', 'セイヨウトチノキ種子エキス', 'オタネニンジン根エキス'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C07',
    name: 'VC美容原液',
    image: 'i3a6a9182adfab2fd',
    category: 'cosmetic',
    description: 'ビタミンC誘導体・ローヤルゼリー・高純度ヒアルロン酸の究極トリプルシナジー美容原液。',
    price: 19800,
    volume: '20ml',
    ingredients: ['ビタミンC誘導体（アスコルビン酸メチルシラノール）', 'ヒアルロン酸Na', '加水分解ローヤルゼリーエキス'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C08',
    name: 'VCエッセンス (脂溶性ビタミンC)',
    image: 'id534e4e4af8f7a70',
    category: 'cosmetic',
    description: '脂溶性ビタミンC誘導体は吸収後、肌自身の酵素によりビタミンＣに変化。肌へのせた瞬間から実感できる美肌ケア。',
    price: 33000,
    volume: '28ml',
    ingredients: ['ビタミンC誘導体（アスコルビン酸メチルシラノール）'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C09',
    name: 'NPエッセンス 30mL',
    image: 'i2fe2601a851111b3',
    category: 'cosmetic',
    description: '世界初ナノ化プラセンタ美容液。「10億分の1」の微粒子となったプラセンタが内側から美しさを作り出す。',
    price: 55000,
    volume: '30ml',
    ingredients: ['プラセンタエキス'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C10',
    name: 'NPエッセンス 10mL',
    image: 'i2fe2601a851111b3',
    category: 'cosmetic',
    description: '世界初ナノ化プラセンタ美容液。お試しサイズ。プラセンタの成長因子が細胞分裂を活発にし新陳代謝をアップ。',
    price: 19800,
    volume: '10ml',
    ingredients: ['プラセンタエキス'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C11',
    name: 'HRローション',
    image: 'i2079cea8bbe18873',
    category: 'cosmetic',
    description: 'ヒアルロン酸でたっぷり保湿！キメを整えハリと弾力のある肌を保つ高保湿ローション。',
    price: 11000,
    volume: '120ml',
    ingredients: ['ヒアルロン酸Na'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C12',
    name: 'ピンクジェル (VPW)',
    image: 'ie2e2e39271962863',
    category: 'cosmetic',
    description: '濃厚美容液ジェルが肌にハリ・潤い・透明感を付与。脂肪に働きかける成分配合でボディケアにもおすすめ。',
    price: 6600,
    volume: '30g',
    ingredients: ['プラセンタエキス', 'ヒアルロン酸Na', '加水分解シルク', 'プエラリアミリフィカ根エキス', 'ビフィズス菌培養溶解質', 'ラクトフェリン(牛乳)', 'ビオチン', 'レシチン', 'Co-Q10(ユビキノン)', 'αリポ酸(チオクト酸)', 'ナツメ果実エキス', 'イチョウ葉エキス', 'ローヤルゼリーエキス'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C13',
    name: 'ファンデーション (クリームタイプ)',
    image: 'ib816af0557a63e43',
    category: 'cosmetic',
    description: 'ハリ・ツヤ・輝きを与えるクリームタイプファンデーション。エッセンス感覚でお使いいただけます。',
    price: 5500,
    volume: '20g',
    ingredients: ['ヒアルロン酸Na', 'ソウハクヒエキス', 'クララエキス', 'チャエキス', 'ベニバナエキス'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C14',
    name: 'スタイリスタボディジェル',
    image: 'ib87f7f2318bea9c3',
    category: 'cosmetic',
    description: '気になるパーツのたるんだお肉をきゅっと引き締め理想のボディラインへ。プラセンタ・CoQ10配合。',
    price: 6600,
    volume: '150g',
    ingredients: ['プラセンタエキス', 'Co-Q10(ユビキノン)', 'ローヤルゼリーエキス', 'プエラリアミリフィカ根エキス', '加水分解シルク', 'αリポ酸(チオクト酸)', 'オウゴン根エキス', 'イチョウ葉エキス', 'ラクトフェリン(牛乳)', 'ビフィズス菌培養溶解質', 'ヒアルロン酸Na', 'ビオチン', 'レシチン'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C15',
    name: 'PJエッセンス (ホホバオイル)',
    image: 'i04d4fcbd16587e7e',
    category: 'cosmetic',
    description: '純度100％ エキストラバージンホホバオイル。浸透性に優れ皮脂バランスを整える。全身・赤ちゃんの肌にも使用可。',
    price: 22000,
    volume: '150ml',
    ingredients: ['ホホバ種子油'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C16',
    name: 'オーガニックリップバーム',
    image: 'ie5365c50eb61709c',
    category: 'cosmetic',
    description: '約20種類のオーガニックハーブ100%の美容成分のみを配合。抜群の保湿力で縦ジワ・乾燥対策にも。防腐剤・アルコール不使用。',
    price: 6600,
    volume: '3g',
    ingredients: ['マカデミア種子油', 'オリーブ果実油', 'スクワラン', 'ミツロウ', 'メドウフォーム油', 'ヒマシ油', 'キャンデリラロウ', 'カルナウバロウ', 'ホホバ種子油', 'アルガニアスピノサ核油', 'アサイヤシ果実油', 'ローズヒップ油', '月見草油', 'ブドウ種子油', 'シア脂', 'トコフェロール'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C17',
    name: 'カンヌ コンディショニングシャンプー',
    image: 'i572ab023301b769a',
    category: 'cosmetic',
    description: '潤いのある健康的な髪・頭皮へ優しく洗いあげる。ヒアルロン酸・ホホバ種子油・褐藻エキス配合。',
    price: 11000,
    volume: '900ml',
    ingredients: ['ホホバ種子油', 'アロエベラ葉エキス', 'ヒアルロン酸Na', '加水分解シルク', '褐藻エキス', 'ツバキ種子油', 'ビフィズス菌培養溶解質', '水溶性コラーゲン'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C18',
    name: 'カンヌ コンディショニングトリートメント',
    image: 'i66ffda9a56763663',
    category: 'cosmetic',
    description: '髪や頭皮の保水性を高め弾力性と柔軟性を補う。水溶性コラーゲン・センブリエキス・高麗人参配合。',
    price: 5500,
    volume: '250g',
    ingredients: ['水溶性コラーゲン', '褐藻エキス', 'センブリエキス', 'オタネニンジン根エキス', '加水分解シルク', 'ヒアルロン酸Na', 'ビフィズス菌培養溶解質', 'ホホバ種子油'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C19',
    name: 'エッセンスシャワー プレミアム',
    image: 'i16d31a2b68acbcc2',
    category: 'cosmetic',
    description: 'ナイアシンアミド・ヒト幹細胞順化培養液を高配合。洗顔・ボディシャンプーとしても安心して使用可。',
    price: 8800,
    volume: '250ml',
    ingredients: ['ナイアシンアミド', 'ヒト幹細胞順化培養液', 'ヒアルロン酸Na', 'ローヤルゼリーエキス', '加水分解シルク', 'イチョウ葉エキス', 'ローズマリー葉エキス', 'ウメ果実エキス', 'アーチチョーク葉エキス', 'ラベンダー油', 'ベルガモット果実油'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C20',
    name: 'ヘアカラートリートメント',
    image: 'id388fc9025b081dc',
    category: 'cosmetic',
    description: 'トリートメントベースで髪や頭皮をいたわりながら染める染毛料。全2色(ナチュラルブラック・モカブラウン)。',
    price: 8800,
    volume: '150g',
    ingredients: ['ヒアルロン酸', 'プラセンタエキス', '尿素', 'ムラサキ根エキス', '加水分解シルク', 'ツバキ種子油', 'バオバブ種子油', 'アルガニアスピノサ核油'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C21',
    name: 'ハーブ入浴剤',
    image: 'ibbe3e33d7e5211af',
    category: 'cosmetic',
    description: 'デトックス・脂肪燃焼・美容効果。7種類のハーブと美容成分配合で入浴後の発汗が持続。',
    price: 5500,
    volume: '300g',
    ingredients: ['キハダ樹皮エキス', 'ショウブ根エキス', 'ヨモギ葉エキス', 'カミツレ花エキス', '甘草エキス', 'オタネニンジンエキス', 'トウキ根エキス'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C22',
    name: 'デンタルジェル',
    image: 'i7b278307b1ed9679',
    category: 'cosmetic',
    description: '歯と歯茎の健康はもちろん身体の健康も考えた歯磨きジェル。ヒドロキシアパタイト・プロポリス配合。',
    price: 3300,
    volume: '100g',
    ingredients: ['ヒドロキシアパタイト(基剤)', 'プロポリスエキス', 'イチョウエキス', 'シコンエキス', 'オウゴンエキス', 'ハッカ油', 'チョウジ油'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C23',
    name: '消臭スプレー 300ml',
    image: 'i9499f28b349360dc',
    category: 'cosmetic',
    description: '消臭効果の高い柿渋と除菌効果のグレープフルーツ種子を主成分。アルコール不使用で安心・安全。',
    price: 4400,
    volume: '300ml',
    ingredients: ['柿渋', 'グレープフルーツ種子'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C24',
    name: '消臭スプレー 50ml',
    image: 'i9499f28b349360dc',
    category: 'cosmetic',
    description: '消臭効果の高い柿渋と除菌効果のグレープフルーツ種子を主成分。携帯サイズ。アルコール不使用。',
    price: 1100,
    volume: '50ml',
    ingredients: ['柿渋', 'グレープフルーツ種子'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C25',
    name: 'モイスチャーマスク',
    image: 'i399c7c655a3ea5db',
    category: 'cosmetic',
    description: '毎日使える新感覚モイスチャーマスク。美容液成分配合で肌を守りながら角質ケア。',
    price: 19800,
    volume: '80g',
    ingredients: ['ビタミンC誘導体(アスコルビン酸メチルシラノール)', 'EGF(ヒトオリゴペプチド-1)', 'リピジュア(ポリクオタニム-51)', 'AHA(リンゴ酸・クエン酸)', 'ヒアルロン酸Na', 'チャ葉エキス', 'オレンジ果皮油', 'オレンジ種子エキス', 'ダイズ油', 'レシチン'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C26',
    name: 'AIM Gel',
    image: 'ie6abf02d0a1f51e8',
    category: 'cosmetic',
    description: '贅沢成分がパーフェクトに配合。約40種類の美肌成分でハリと弾力のある肌本来の輝きをサポート。',
    price: 22000,
    volume: '50g',
    ingredients: ['ビタミンC誘導体(アスコルビン酸メチルシラノール)', 'リピジュア(ポリクオタニム-51)', 'αリポ酸(チオクト酸)', 'プラセンタエキス', 'Ｃo-Ｑ１０(ユビキノン)', 'EGF(ヒトオリゴペプチド-1)', 'FGF(ヒトオリゴペプチド-13)', 'IGF(ヒトオリゴペプチド-21)', 'ヒアルロン酸Na', '加水分解シルク', 'プエラリアミリフィカ根エキス', 'オウゴン根エキス', 'ピクノジェノール(フランスカイガンショウ樹皮エキス)', 'ビフィズス菌培養溶解質', 'ラクトフェリン(牛乳)', 'ビオチン', 'カルニチン', 'ツボクサエキス', 'アテロコラーゲン', 'コンドロイチン硫酸Na', '月見草油', 'ナツメ果実エキス', 'イチョウ葉エキス'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C27',
    name: '美容液ソープ 300ml',
    image: 'i8d52319c799a8875',
    category: 'cosmetic',
    description: 'クレンジング・洗顔・ボディソープ・シャンプーがこれ1本でOK。石油系成分不使用のヤシ油系美容液ソープ。',
    price: 19800,
    volume: '300ml',
    ingredients: ['ビタミンC誘導体(アスコルビン酸メチルシラノール)', 'EGF(ヒトオリゴペプチド-1)', 'リピジュア(ポリクオタニム-51)', 'ヒアルロン酸Na', '月見草油', 'ユビキノン', 'カルニチン', 'ナツメ果実エキス', 'イチョウ葉エキス', 'チャ葉エキス', 'ツボクサエキス', 'ラクトフェリン(牛乳)', 'アテロコラーゲン', 'ヒバマタエキス', 'コンドロイチン硫酸Na', 'レシチン', '加水分解シルク'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
  {
    id: 'C28',
    name: '美容液ソープ 52ml',
    image: 'i8d52319c799a8875',
    category: 'cosmetic',
    description: 'クレンジング・洗顔・ボディソープ・シャンプーがこれ1本でOK。石油系成分不使用。携帯サイズ。',
    price: 4400,
    volume: '52ml',
    ingredients: ['ビタミンC誘導体(アスコルビン酸メチルシラノール)', 'EGF(ヒトオリゴペプチド-1)', 'リピジュア(ポリクオタニム-51)', 'ヒアルロン酸Na', '月見草油', 'ユビキノン', 'カルニチン', 'ナツメ果実エキス', 'イチョウ葉エキス', 'チャ葉エキス', 'ツボクサエキス', 'ラクトフェリン(牛乳)', 'アテロコラーゲン', 'ヒバマタエキス', 'コンドロイチン硫酸Na', 'レシチン', '加水分解シルク'],
    symptoms: [],
    effects: [],
    nutrientIds: [],
    memo: '',
    createdAt: new Date('2026-05-26'),
  },
]

export const IMAGE_BASE = 'https://image.jimcdn.com/app/cms/image/transf/none/path/s6d4d15d6e7c4e3f7/image/'

export function productImageUrl(imageId: string): string {
  if (!imageId) return ''
  return `${IMAGE_BASE}${imageId}/version/1744688141/image.jpg`
}
